[package]
name = "whisper"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
default = ["torch-backend"]
torch-backend = ["burn-tch", "burn/tch"]
wgpu-backend = ["burn-wgpu", "burn/wgpu"]

[dependencies]
burn = {version = "0.12.1", optional = true}
burn-tch = {version = "0.12.1", optional = true}
burn-wgpu = {version = "0.12.1", optional = true}

serde = {version = "1", features = ["std", "derive"]}
num-traits = "0.2.15"
hound = "3.5.0"
tokenizers = {version = "0.15.2", default-features = false, features = [
  "onig",
  "http",
]}
npy = "0.4.0"
cfg-if = "1"
strum = "0.26.1"
strum_macros = "0.26.1"
